### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by thvd** [mafintosh/chromecasts#1]
I want to use [Sourcegraph](https://sourcegraph.com) for chromecasts code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/mafintosh/chromecasts. (It should only take 30 seconds.)

Thank you!

**Comment by therealklanni** [comment]
Why?

**Comment by thvd** [comment]
That way I can browse your code using Sourcegraph. But to be clear, it would be nice, no needed for me.

**Comment by therealklanni** [comment]
Sorry if I came across as rude, I was just wondering how this would be useful.

**Comment by thvd** [comment]
If you enable this repository you can browse it on Sourcegraph. If you want to see how it works check this out: https://sourcegraph.com/github.com/gulpjs/gulp@4d35560d9e2e992037886897c671518cfe49fd7f/.tree/index.js#selected=11 (for example)

Also take a look at this blog post if you want to know more: https://sourcegraph.com/blog/117780211179
