### ISSUE TITLE
Remove native dependency

### ISSUE THREAD

**Issue by feross** [mafintosh/chromecasts#10]
Is there anything we can do to remove the native dependency when installing `chromecasts`?

```
> dtrace-provider@0.5.0 install /Users/feross/code/webtorrent/node_modules/chromecasts/node_modules/node-ssdp/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js
```

Looks like it comes from `node-ssdp` depending on `bunyan`.

**Comment by mafintosh** [comment]
I'd be fine with just removing ssdp support until it can be done in native js. Send a PR :)

**Comment by feross** [comment]
This is fixed now! I got `node-ssdp` to remove their native dependency in 2.7.0 a while ago.
