### ISSUE TITLE
mDNS discovery not working (PTR vs. A record "name" property mismatch)

### ISSUE THREAD

**Issue by romaincointepas** [mafintosh/chromecasts#27]
The PTR record name property looks like this:
`Chromecast-1930a236896105d6f9026ddc5e85e3a8._googlecast._tcp.local`

And the A record name property looks like this:
`1930a236-8961-05d6-f902-6ddc5e85e3a8.local`

After the replace done in the code, we end up with:
PTR: `Chromecast-1930a236896105d6f9026ddc5e85e3a8`
A: `1930a236-8961-05d6-f902-6ddc5e85e3a8`

To `emit()` a device, there is a condition that fails is the 2 above string are not the same.

When testing with a Chromecast 2nd gen, well, they are never the same.

I'm wondering if this issue is specific to:
- my Chromecast (that would be weird, and mean)
- a group of Chromecasts 2nd generation, or all Chromecasts 2nd generation
- a recent Chromecast firmware update (either affecting a specific generation, or all generations)
- Chromecasts only, or other Cast-compatible devices (Android TV, etc.)

Thoughts?

Note: It would help if anyone with a Cast-enabled device could check their mDNS response, see if they see the same thing.

(@feross, you said in another issue that you have a Chromecast Audio).

**Comment by jmsaulnier** [comment]
yep I have the same issue (Chromecast 2nd generation) but it was working before and stopped to work around October / November, so probably a Chromecast firmware update

**Comment by jmsaulnier** [comment]
I don't have a Chromecast 1st gen or Chromecast audio to test 
https://github.com/jmsaulnier/chromecasts/tree/chromecast-2nd-gen

**Comment by feross** [comment]
I have a Chromecast 2nd-gen video as well as audio to test with. Is there a code sample to test this? Or, which line of code should I add a `console.log` to?

**Comment by jmsaulnier** [comment]
@feross Added example on my branch to play a video (npm run example)

**Comment by tonyhawz** [comment]
This is fixed at #29 
I have tested it with an Android Tv device (mi box 3)
