### ISSUE TITLE
No MDNS being sent.

### ISSUE THREAD

**Issue by nevercast** [mafintosh/chromecasts#4]
Hello @mafintosh 

Foremostly, thank you for all your work regarding streaming & peer-peer work. I use a lot of your modules.

When attempting to get a list of players, .update() never dispatches an mDNS query and when rebooting the Chromecast the published mDNS messages are not received by 'chromecasts'.

```
var casts = require('chromecasts')();
casts.on('update', function(player) { console.log('Update', player); });
// Force an update to attempt to see the message in Wireshark
casts.update();
// Wait an ample amount of time.
setTimeout(function() {
  console.log('Players:', casts.players);
}, 10000);
```

The update is never fired and the players is an empty array. I can communicate with my Chromecast just fine with Chrome Browser or Android. Wireshark shows Chromecast pushing replies when queried by other devices but Node.JS never dispatches a query and doesn't seem to receive any passive messages from the Chromecast when the device is booted.

Node: v0.12.2
NPM: v2.7.4
Chromecasts: 1.4.0 @650768ffd6
OS: Windows 8.1.1 (x64)

I've tested running as User and Administrator to no avail. I do not see an mDNS query published when calling update.

**Comment by beaugunderson** [comment]
can you test at 1.3.1 just to verify that i didn't break everything by enabling ssdp? :)

**Comment by nevercast** [comment]
Not a problem, give me a few moments.

**Comment by beaugunderson** [comment]
anecdotally i've noticed that basically every node lib, using `dig`, using bonjour browser/etc. can no longer find my chromecast (on current fw) via mdns (which is why i added ssdp, which does find it without issue)

it would also be great to know the firmware version of your chromecast (visible in the iOS app and i assume the android app)

**Comment by beaugunderson** [comment]
also if you run with DEBUG=mdns* in your environment you'll get some additional information that could be helpful to diagnose :)

**Comment by nevercast** [comment]
Firmware Version: 27946

Downgrading to 1.3.1 didn't help. I'll try with the Environment Variable.

**Comment by nevercast** [comment]
Setting DEBUG to mdns made no changes and nothing was printed to stdout or stderr, does the diagnosis go elsewhere?

Wireshark is still showing no mDNS leaving my PC.

**Comment by nevercast** [comment]
Disabled Firewall and AV, Confirmed that neither of these are causing it. I'll try this again with v1.4.0

**Comment by nevercast** [comment]
Debugging is visible in 1.4.0, I'll redirect it and paste it here shortly.

**Comment by beaugunderson** [comment]
ah, sorry, yes, 1.4.0 is where the DEBUG logic got added :)

**Comment by beaugunderson** [comment]
in wireshark can you verify your filter? i think `ip.dst == 5353` should get everything

**Comment by nevercast** [comment]
That's an invalid filter. 

I used the following filters:
http://i.imgur.com/NDat11B.png

http://i.imgur.com/jgMlch4.png

**Comment by nevercast** [comment]
Had to strip the escape codes, sorry for delay. Here is the mdns log.
http://pastebin.com/teGH2zXX

**Comment by beaugunderson** [comment]
here's what i get with tcpdump:

```
$ tcpdump -i en0 -s0 -n dst port 5353
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on en0, link-type EN10MB (Ethernet), capture size 65535 bytes
15:22:45.775508 IP 192.168.1.39.5353 > 224.0.0.251.5353: 0 [1a] PTR (QM)? _googlecast._tcp.local. (66)
15:22:45.775701 IP6 fe80::baf6:b1ff:fe15:4885.5353 > ff02::fb.5353: 0 [1a] PTR (QM)? _googlecast._tcp.local. (66)
```

**Comment by beaugunderson** [comment]
so i tried this a bunch of times and sometimes it doesn't work (and that it also didn't always work in 1.3.1)

**Comment by nevercast** [comment]
I'm using `udp.port eq 5353` as my Filter which is the same as your tcpdump. Still an empty list unfortunately.

I'll try using multicast-dns and ssdp standalone in their own tests and see if anything shows up.

**Comment by beaugunderson** [comment]
sorry, the multicast debug is actually under DEBUG=multicast-dns (or multicast-* or just * for everything, though that pulls in the debug logs for `request` too); though maybe not much more useful

there's another open bug in multicast-dns (for AAAA records) so i'm interested in shoring it up a bit too :)

**Comment by nevercast** [comment]
I'll disable IPv6 across my network and see if this makes a different.

**Comment by nevercast** [comment]
Pulled down IPv6 on my network (Took a moment as that is three routers).

Chromecast is now showing up :)

**Comment by beaugunderson** [comment]
interesting! so maybe that directly implicates that open bug on multicast-dns

(i have native IPv6 on my network fwiw)

**Comment by nevercast** [comment]
IPv6 was already disabled on my PC but not disabled on my Network hardware, It's perhaps possible that the Chromecast subscribed to it's multicast on an IPv6 address. I've no idea to be honest as Wireshark was entirely empty for both IPv4 and IPv6

**Comment by nevercast** [comment]
You and mafintosh are both aware of the AAAA issue but I'll drop it here for a weak-reference.
https://github.com/mafintosh/multicast-dns/issues/7

**Comment by nevercast** [comment]
FYI: Downgrading to 1.3.1 worked what seems to be 100 percent of the time with IPv6 off also.

**Comment by beaugunderson** [comment]
@nevercast multicast-dns 2.1.1 is out with a fix for the AAAA issue, if you blow away node_modules and npm install then you should get a chomecasts with the latest multicast-dns and be able to turn IPv6 back on in your network :)

**Comment by nevercast** [comment]
Just letting you know I've seen the comment and will re-enable IPv6 tonight and test. Thanks again.
